# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2388b7bc54df61b266d599eb85face3cb98741d5f012fc0c6a5f85108d9ba0c8980fcdee9ee1e83e637c7f32d351e469ab512a107c51c48cc6c76293868d919

test:
  secret_key_base: 27a3b4c2d372b57e7d1a8f03e569bdce3a678a881cad39bcd8aa824a690e12711344a87d6977beb2e17a685a23f6c03fd6048784e302a854c1ff4be77c7236e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
